[package]
name = "furry_crypto"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
aes-gcm.workspace = true
blake3.workspace = true
hkdf.workspace = true
sha2.workspace = true
thiserror.workspace = true
zeroize.workspace = true
getrandom.workspace = true
