name: furry_flutter_templates
description: Internal template sources for Furry Player Flutter app generation.
publish_to: "none"
version: 0.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.3.2
  path_provider: ^2.1.5
  just_audio: ^0.9.46
  just_audio_platform_interface: ^4.4.0
  path: ^1.9.0
  ffi: ^2.1.3
  just_audio_background: ^0.0.1-beta.15
  audio_service: ^0.18.17
  smtc_windows: ^1.0.0
  dbus: ^0.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
